classDiagram
class PreEditContext{
    selStart int32
    selEnd int32
    content wstring
}
class CompositionState{
    Start
    Update
    End
}
class PreEditCallback

class PreEditRect{
    left int32
    top int32
    right int32
    bottom int32
}
class PreEditRectCallback

class CandidateListContext{
    selection int32
    candidates list_wstring

    setSelection(int32)
    setFinalize()
}
class CandidateListState{
    Start
    Update
    End
}
class CandidateListCallback

class CommitCallback

class ICallback{
    callback functional_F
    setCallback(functional_F)
    runCallback(T...)
}
class Composition{
    terminate()
}
class InputContext{
    composition Composition

    setActivated(bool)
    getActivated() bool
    setFullScreen(bool)
    getFullScreen() bool
}

class Locale{
    locale wstring
    name wstring
}
class InputProcessor{
    type InputProcessorType
    locale Locale
    name wstring

    setActivated()
}
class InputProcessorType{
    KeyboardLayout
    TextService
}
class InputProcessorState{
    InputModeUpdate
    FullUpdate
}
class InputProcessorContext{
    inputProcessor InputProcessor
    inputModes list_InputMode
}
class Global{
    getActiveInputProcessor() InputProcessorContext
    getInputProcessors() list_InputProcessor
    getInputContext(...) InputContext
}

InputContext *-- Composition

PreEditCallback --> CompositionState
PreEditCallback --> PreEditContext
PreEditCallback ..|> ICallback

PreEditRectCallback --> PreEditRect
PreEditRectCallback ..|> ICallback

CandidateListCallback ..|> ICallback
CandidateListCallback --> CandidateListState
CandidateListCallback --> CandidateListContext

CommitCallback ..|> ICallback

Composition --|> PreEditCallback
Composition --|> PreEditRectCallback
Composition --|> CommitCallback
Composition --|> CandidateListCallback

InputProcessorCallback --> InputProcessorState
InputProcessorCallback --> InputProcessorContext
InputProcessorCallback ..|> ICallback

InputProcessor *-- InputProcessorType
InputProcessor --> Locale

InputProcessorContext --> InputProcessor

Global --> InputProcessorContext
Global --> InputProcessor
Global --|> InputProcessorCallback